services:
  hugo:
    container_name: hugo
    ports:
      - "8081:8081"
    build:
      context: .
      target: build
    volumes:
      - ${PWD}/content:/src/content
      - ${PWD}/layouts:/src/layouts
    command:
      - server
      - --enableGitInfo
      - --bind=0.0.0.0
      - --port=8081
      - --buildDrafts
