version: 2.1

orbs:
  architect: giantswarm/architect@5.15.0

workflows:
  version: 2

  build_and_update:
    jobs:
    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        filters:
            # Trigger job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        executor: app-build-suite
        app_catalog: giantswarm-operations-platform-catalog
        app_catalog_test: giantswarm-operations-platform-test-catalog
        chart: handbook
        requires:
        - push-to-registries
        filters:
            # Trigger job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
