kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: handbook
  labels:
    app: handbook
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: handbook
