apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: handbook
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: handbook

  unhealthyPodEvictionPolicy: AlwaysAllow
