{{ $this := . }}
{{ range $index, $secret := .Values.Secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret.name }}
  namespace: {{ include "resource.default.namespace" $this }}
  labels:
    {{- include "labels.common" $this | nindent 4 }}
data:
  {{ range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{ end }}
{{ end }}
