kind: Service
apiVersion: v1
metadata:
  namespace: intranet
  name: staticjscms-hugo-standalone
  labels:
    app: staticjscms-hugo-standalone
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: staticjscms-hugo-standalone
