staticJsCmsHugoStandaloneVersion: v0.0.1

Secrets:
  # Information for staticjscms-hugo-standalone and its OAuth proxy component
  - name: staticjscms-secret
    data:
      ORIGIN: aHR0cHM6Ly9oYW5kYm9vay5naWFudHN3YXJtLmlv
      OAUTH_CLIENT_ID: MjE5OTEyMzk5MWFzZGVhZGJlZWY=
      OAUTH_CLIENT_SECRET: YWFkc3NhZGFkYWRhZGFkMTIzMTIzMTIzMWFkYWRhZDEyMzEyM2FiYw==
      GIT_HOSTNAME: ""
