name: Check Markdown links
on: push
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository content
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          show-progress: false

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check@3.11.2

      - name: Run markdown-link-check
        run: |
          find content/docs -type f -name '*.md' | \
              xargs markdown-link-check \
                --quiet \
                --config ./.github/workflows/markdown-link-check.json
