name: Render RFCs and create/update PR on changes

on:
  schedule:
    - cron: "0 7-18 * * MON-FRI"

  push:

jobs:
  render-rfcs-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: handbook

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'giantswarm/rfc'
          path: rfc

      - name: Render RFCs
        env:
          RFCS_DIR: "${{ github.workspace }}/rfc"
        run: make rfcs
        working-directory: "${{ github.workspace }}/handbook"

      - name: Create or update pull request
        uses: gr2m/create-or-update-pull-request-action@v1.9.2
        if: ${{ github.ref == 'refs/heads/rfcs' }} # TODO: replace by `refs/heads/main` later
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          title: Update generated RFCs content
          branch: "update-generated-rfcs-content"
          body: |
            This PR has been created automatically by the 'Render RFCs and create/update PR on changes' GitHub workflow
            to keep rendered RFCs in the handbook up to date.

            Please review and merge, or check in `#sig-docs` chat if something is wrong.
          reviewers: AndiDog  # TODO: while this is being tested, replace by team reviewer later
          #team_reviewers: giantswarm/sig-docs
